### ISSUE TITLE
Add another newline

### ISSUE THREAD

**Issue by patlillis** [ianunay/sublime_scratchpad#3]
If the user left the scratchpad.txt file without an empty line at the end, then adding a new note causes the new timestamp to run up against the previous text:

![image](https://cloud.githubusercontent.com/assets/2921735/12677694/c9dc8a22-c668-11e5-9614-b17cba231946.png)

One way of fixing this would be to insert 2 newlines, that way there will always be space between the previous note and the new one

**Comment by ianunay** [comment]
Fixed in 3f1966a
